### ISSUE TITLE
WrapFit package - Lower Flutter version

### ISSUE THREAD

**Issue by matiasilveiro** [fischerscode/pub.packages#1]
### Description
Currently, the "WrapFit" package requires a minimum Dart SDK version of 3.3.0 (available in Flutter 3.19.0). However, I have tested the package with Flutter SDK version 3.16.6 and it works perfectly fine.

I would like to request the owner of the repository to consider lowering the minimum Flutter SDK version requirement to 3.16.6 or lower, to allow more users who are on older versions of Flutter to benefit from this package.

### Steps to Reproduce (if applicable)
1. Install Flutter SDK version 3.16.6.
2. Import and use the "WrapFit" package in a Flutter project.
3. Observe that the package works as expected.

### Expected Behavior
Lowering the minimum Flutter SDK version requirement would make the package compatible with a wider range of Flutter versions, enabling more users to utilize its functionality.

### Additional Information
- Flutter version used: 3.16.6
- Other relevant information, screenshots, or code snippets that may assist in resolving this issue.

Thank you for considering this suggestion. I believe it would benefit many users who are unable to upgrade to the latest Flutter version.

**Comment by matiasilveiro** [comment]
Amazing package by the way! In the past I made my own custom _RenderObject_ for this functionality (to expand only the last child), but your solution is much more scalable! I appreciate it 🚀

**Comment by fischerscode** [comment]
Nice catch. I've lowered the lower dart version `3.0.0` and published version `0.1.1`.

I'm sorry that this had to take so long. I didn't notice this issue. I this was not a huge problem for you.
